version: '2.5'
services:
      app:
        container_name: api_go
        image: api_go
        build:
         context: .
         dockerfile: Dockerfile
         
        volumes:
           - .:/go_app
        ports:
          - "8080:8080"
        

